# Import Library & Data

In [3]:
import pandas as pd

In [4]:
dokter_feb = pd.read_csv('dokter_feb.csv')

In [5]:
dokter_feb

,NO_REG,NAMA,TGL_LAHIR_F,JENIS_KELAMIN,UMUR_TAHUN,UMUR_BULAN,UMUR_HARI,NM_UNIT,ASESMEN,SUBYEKTIF,OBYEKTIF,KD_PENYAKIT,NM_PENYAKIT
0,10510023,NaN,06/04/1958,L,67.0,2.0,15.0,POLI UMUM,Abdominal pain,pasien datang dengan keluhan pusing sejak pagi...,"KU sedang, CM\r\nTD 195/98\r\nN 89\r\nS 36.8\r...",R10,Abdominal and pelvic pain
1,10578834,NaN,22/01/2015,P,11.0,0.0,10.0,SPES. GIGI PEDODONTIS,36 : K04.1 NECROSIS OF PULP \r\n,36 : gigi sudah tidak sakit \r\n,36 : Caries\r\n \r\n,K04.1,Necrosis of pulp
2,10578962,NaN,15/07/1956,L,69.0,6.0,19.0,SPES. SARAF,"Post stroke infark, Dizziness ec neuropati oto...",Keluhan Utama : Kontrol\r\nnyeri leher sampai ...,Kesadaran : 0: Sadar Baik \r\nRisiko jatuh : T...,I63.9,"Cerebral infarction, unspecified"
3,10579356,NaN,10/05/1963,P,62.0,8.0,26.0,SPES. PENYAKIT DALAM,Non-insulin-dependent diabetes mellitus\r\n Es...,"\r\n\r\nkontrol rutin, kesmeutan (-) pusing (...",Kesadaran : 0: Sadar Baik \r\nRisiko jatuh : T...,E11.4,Non-insulin-dependent diabetes mellitus with n...
4,10579458,NaN,17/11/2015,P,10.0,2.0,15.0,SPES. GIGI PEDODONTIS,84 : K08.3 RETAINED DENTAL ROOT \r\n,84 : sundulan \r\n,"84 : Caries,Tambalan\r\n \r\n",K08.3,Retained dental root
...,...,...,...,...,...,...,...,...,...,...,...,...,...
8278,10600255,NaN,07/11/2006,P,19.0,3.0,21.0,UGD,Multiple VE\r\nObs CKR,Riwayat penyakit sekarang : Pasien datang deng...,Keadaan Umum : BAIK \rKondisi Fisik : CUKUP \r...,S06.0,Concussion
8279,10600256,NaN,13/01/1987,P,39.0,1.0,15.0,POLI UMUM,Cholelithiasis,Riwayat penyakit sekarang : Pasien kontrol rut...,Keadaan Umum : SEDANG \r\nKondisi Fisik : CUKU...,K80,Cholelithiasis
8280,10600257,NaN,01/12/1999,L,26.0,2.0,28.0,POLI UMUM,Obs febris H3,Pasien datang dengan keluhan badan terasa greg...,"KU baik CM\r\nTD 155/86\r\nN 88\r\nT 37,2\r\nS...",R50.9,"Fever, unspecified"
8281,10600258,NaN,17/08/1977,L,48.0,6.0,12.0,POLI UMUM,Bell's palsy,Pasien datang dengan keluhan wajah kiri terasa...,"KU baik CM\r\nTD 140/93\r\nN 66\r\nT 36,7\r\nR...",G51.0,Bell's palsy
8282,10600259,NaN,15/06/1976,P,49.0,8.0,14.0,POLI UMUM,LBP post jatuh,Pasien datang dengan keluhan boyok terasa nyer...,KU baik CM\r\nTD 134/83\r\nN 107\r\nT 36\r\nSp...,M54.5,Low back pain

In [6]:
dokter_maret = pd.read_csv('dokter_maret.csv')

In [7]:
dokter_maret

,NO_REG,NAMA,TGL_LAHIR_F,JENIS_KELAMIN,UMUR_TAHUN,UMUR_BULAN,UMUR_HARI,NM_UNIT,ASESMEN,SUBYEKTIF,OBYEKTIF,KD_PENYAKIT,NM_PENYAKIT
0,10578122,NaN,22/05/2025,L,0.0,9.0,11.0,POLI VAKSIN,IMUNISASI MR PADA ANAK\r\nSTUNTING,IMUNISASI MR PADA ANAK,BB 4.8 >> 5.2 >> 6.1 >> 6.8 >> 7.16 >> 7.4 < -...,Z26.9,Need for immunization against unspecified infe...
1,10587434,NaN,13/04/2016,P,9.0,10.0,24.0,SPES. GIGI PEDODONTIS,36 : K04.0 PULPITIS \r\n,36 : GIGI BERLUBANG \r\n,36 : Caries\r\n \r\n,K04.0,Pulpitis
2,10588781,NaN,13/03/2025,L,1.0,0.0,3.0,POLI VAKSIN,IMUNISASI VARICELLA PADA ANAK,IMUNISASI VARICELLA PADA ANAK,BB 5.4 >> 6.7 >> 7.4 >> 7.9 >> 8 (SEMPAT SAKIT...,Z23,Need for immunization against single bacterial...
3,10588852,NaN,14/07/1998,P,27.0,7.0,20.0,SPES. OBSGYN,G1P0A0 UK 16+1 MG,Keluhan Utama : G1P0A0 UK 16+1 MG\r\n \r\nHPHT...,Kesadaran : 0: Sadar Baik \r\nRisiko jatuh : T...,Z35,Supervision of high-risk pregnancy
4,10588947,NaN,20/03/1966,P,59.0,11.0,13.0,SPES. MATA,OD SUBKONJ HEMORRHGAE SPONTAN,KONTROLO\r\nMATA KANAN SH TDK MERAH,"\r\nOD= DKM 6/9, KON HEMORHGE+, KORNEA JENRIH,...",H11.3,Conjunctival haemorrhage
...,...,...,...,...,...,...,...,...,...,...,...,...,...
7956,10610205,NaN,31/12/1967,L,58.0,2.0,27.0,POLI UMUM,Susp. ISK dd BSK,Pasien datang dengan keluhan nyeri perut bawa...,"TD: 146/96\r\nN: 71\r\nRR: 20\r\nS: 36,7\r\nSp...",N39.0,"Urinary tract infection, site not specified"
7957,10610206,NaN,07/01/2010,L,16.0,2.0,20.0,POLI UMUM,RFA,pasien datang dengan keluhan nyeri tenggorokan...,"KU sedang CM\r\nTD 119/78\r\nN 84\r\nS 36,4\r\...",J31,"Chronic rhinitis, nasopharyngitis and pharyngitis"
7958,10610207,NaN,14/04/1972,P,53.0,11.0,13.0,POLI UMUM,Cephalgia\r\nVertigo perifer,Pasien datang dengan keluhan nyeri kepala ceko...,"TD: 120/63\r\nN: 84\r\nRR: 20\r\nS: 36,6\r\nSp...",H81.4,Vertigo of central origin
7959,10610208,NaN,04/03/1970,L,56.0,0.0,25.0,POLI UMUM,VL pedis dextra post hecting H9,Keluhan Utama : KONTROL RAWAT LUKA LEPAS BENAN...,Kesadaran : 0: Sadar Baik \r\nRisiko jatuh : T...,S91.3,Open wound of other parts of foot
7960,10610210,NaN,09/02/2004,P,22.0,1.0,18.0,POLI UMUM,G1P0A0 Uk 40mg+3,"pasien datang dengan keluhan kenceng kenceng, ...",KU sedang CM\r\nTD 120/63\r\nN 84\r\nR 20\r\nS...,Z35,Supervision of high-risk pregnancy

In [8]:
dokter_april = pd.read_csv('dokter_april.csv')

In [9]:
dokter_april

,NO_REG,NAMA,TGL_LAHIR_F,JENIS_KELAMIN,UMUR_TAHUN,UMUR_BULAN,UMUR_HARI,NM_UNIT,ASESMEN,SUBYEKTIF,OBYEKTIF,KD_PENYAKIT,NM_PENYAKIT
0,10585674,NaN,20/03/1986,L,39,10,1,KOMPLEMENTER,NaN,NaN,NaN,NaN,NaN
1,10594770,NaN,04/12/2019,P,6,3,29,SPES. GIGI PEDODONTIS,75 : K04.0 PULPITIS \r\n,75 : gigi GIGI BERLUBANG \r\n,"75 : Caries,Tambalan\r\n \r\n",K04.0,Pulpitis
2,10596059,NaN,20/09/2017,L,8,6,28,SPES. GIGI PEDODONTIS,52 : K04.1 NECROSIS OF PULP \r\n,"52 : kesundulan, GIGI GOYANG \r\n",52 : Gigi goyang\r\nder 1 \r\n,K04.1,Necrosis of pulp
3,10597730,NaN,01/07/1995,P,30,9,1,SPES. OBSGYN,G4P1A2 UK 20+6 MG\r\nemesis gravidarum\r\nplas...,Keluhan Utama : G4P1A2 UK 20+6 MG\r\n \r\nHPHT...,Kesadaran : 0: Sadar Baik \r\nRisiko jatuh : T...,O21.0,Mild hyperemesis gravidarum
4,10598456,NaN,12/02/2000,P,26,2,6,SPES. OBSGYN,O90.1 - Disruption of perineal obstetric wound,Keluhan Utama : jahitan post partum terbuka\r\...,Kesadaran : 0: Sadar Baik \r\nRisiko jatuh : T...,O90.1,Disruption of perineal obstetric wound
...,...,...,...,...,...,...,...,...,...,...,...,...,...
6462,10619554,NaN,11/05/1975,L,50,11,11,POLI UMUM,ulkus dm,kontrol luuka post debridemt ulkus dm,NaN,NaN,NaN
6463,10619561,NaN,13/04/1976,P,50,0,8,UGD,Obs. dyspneu ec asma serangan sedang,Riwayat penyakit sekarang : Pasien datang deng...,Keadaan Umum : SEDANG \rKondisi Fisik : CUKUP ...,NaN,NaN
6464,10619567,NaN,20/10/1987,P,38,6,1,HEMODIALISA,NaN,NaN,NaN,N18,Chronic kidney disease
6465,10619578,NaN,10/01/2010,L,16,3,10,POLI UMUM,Post NE H3,"Pasien datang untuk kontrol rawat luka, saat i...",Luka bersih,NaN,NaN
6466,10619595,NaN,19/04/1955,L,71,0,3,POLI UMUM,ispa\r\ndyspepsia,"batuk disertai demam sdh bbrp hari, nyeri ulu ...","s 36,3\r\nt 128/74\r\nn 79\r\nspo2 97 98",NaN,NaN

## Feature Engineering(For Dashboard)

In [10]:
dokter_feb['bulan'] = 'Februari'
dokter_maret['bulan'] = 'Maret'
dokter_april['bulan'] = 'April'

## Merge Table

In [11]:
df_dokter_all = pd.concat(
    [dokter_feb, dokter_maret, dokter_april],
    ignore_index=True
)

In [12]:
df_dokter_all.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 22711 entries, 0 to 22710
Data columns (total 14 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   NO_REG         22711 non-null  int64
 1   NAMA           0 non-null      float64
 2   TGL_LAHIR_F    22711 non-null  object
 3   JENIS_KELAMIN  22711 non-null  object
 4   UMUR_TAHUN     22709 non-null  float64
 5   UMUR_BULAN     22709 non-null  float64
 6   UMUR_HARI      22709 non-null  float64
 7   NM_UNIT        22711 non-null  object
 8   ASESMEN        19245 non-null  object
 9   SUBYEKTIF      19334 non-null  object
 10  OBYEKTIF       19178 non-null  object
 11  KD_PENYAKIT    22057 non-null  object
 12  NM_PENYAKIT    22057 non-null  object
 13  bulan          22711 non-null  object
dtypes: float64(4), int64(1), object(9)
memory usage: 2.4+ MB

In [13]:
df_dokter_all.duplicated().sum()

np.int64(0)

In [14]:
df_dokter_all.to_csv('dokter_all.csv', index=False)

# Cleaning Data

In [15]:
df_dokter_all['NM_UNIT'].unique()

array(['POLI UMUM ', 'SPES. GIGI PEDODONTIS', 'SPES. SARAF',
       'SPES. PENYAKIT DALAM', 'SPES. MATA', 'SPES. JIWA', 'SPES. OBSGYN',
       'SPES. ANAK', 'JANTUNG DAN PEMBULUH DARAH', 'SPES. PARU PARU',
       'MARWA 18', 'SPES. GIGI ENDODONSI', 'UGD', 'MARWA 1',
       'POLI VAKSIN', 'TRANSIT MARWA 1', 'SPES. BEDAH', 'AROFAH 12',
       'AROFAH 17', 'SPES. THT', 'POLI BIDAN', 'AROFAH 8', 'MARWA 4',
       'AROFAH 10', 'AROFAH 1', 'AROFAH 3', 'KBY III', 'KBY II',
       'KOMPLEMENTER', 'MARWA 3', 'AROFAH 16', 'KBY I', 'MARWA 15',
       'MARWA 20', 'MARWA 6', 'AROFAH 13', 'MARWA 13', 'MARWA 14',
       'AROFAH 6', 'MARWA 10', 'MARWA 2', 'KBY V', 'AROFAH 7',
       'AROFAH 14', 'AROFAH 4', 'AROFAH 11', 'MARWA 8', 'MARWA 5',
       'MARWA 17', 'MARWA 19', 'POLI FISIOTERAPI', 'MARWA 16', 'KBY X',
       'AROFAH 5', 'POLI GIGI', 'OBAT ITERASI', 'MARWA 11', 'MARWA 12',
       'AROFAH 2', 'HEMODIALISA', 'AROFAH 15', 'MARWA 7',
       'POLI RAWAT LUKA', 'IBS', 'HOME CARE', 'MARWA 9', 'KBY IV',
       'LABORATORIUM', 'HOME VISITE', 'AROFAH 9', 'RADIOLOGI',
       'ZAM - ZAM 6', 'ZAM - ZAM 5', 'SHAFA 5 ISOLASI',
       'KONSULTASI ONLINE', 'KBY XII', 'POLI AKUPUNTUR', 'ZAM - ZAM 4',
       'SHAFA 10', 'ZAM - ZAM 2', 'VK 4', 'MARWA 21', 'KBY VI', 'KBY VII',
       'KBY XI', 'MARWA 22', 'KBY VIII', 'KBY IX', 'POLI KHITAN',
       'SHAFA ICU 01', 'ZAM - ZAM 1', 'ZAM - ZAM 3', 'VK 1',
       'SPES. KULIT DAN KELAMIN', 'SHAFA ICU 05'], dtype=object)

In [16]:
selected_unit = [
    'SPES. PENYAKIT DALAM',
    'SPES. PARU PARU',
    'JANTUNG DAN PEMBULUH DARAH'
]

df_dokter_filtered = df_dokter_all[
    df_dokter_all['NM_UNIT'].isin(selected_unit)
]

In [17]:
df_dokter_filtered = df_dokter_filtered.drop(columns=['NAMA'])

In [18]:
df_dokter_filtered.info()

<class 'pandas.core.frame.DataFrame'>
Index: 4281 entries, 3 to 22639
Data columns (total 13 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   NO_REG         4281 non-null   int64
 1   TGL_LAHIR_F    4281 non-null   object
 2   JENIS_KELAMIN  4281 non-null   object
 3   UMUR_TAHUN     4281 non-null   float64
 4   UMUR_BULAN     4281 non-null   float64
 5   UMUR_HARI      4281 non-null   float64
 6   NM_UNIT        4281 non-null   object
 7   ASESMEN        4252 non-null   object
 8   SUBYEKTIF      4280 non-null   object
 9   OBYEKTIF       4260 non-null   object
 10  KD_PENYAKIT    4257 non-null   object
 11  NM_PENYAKIT    4257 non-null   object
 12  bulan          4281 non-null   object
dtypes: float64(3), int64(1), object(9)
memory usage: 468.2+ KB

Cek Jumlah Pasien yang periksa lebih dari 1 kali

In [19]:
(df_dokter_filtered['NO_REG'].value_counts() > 1).sum()

np.int64(0)

Cek Jumlah Pasien yang periksa ke berbagai unit

In [20]:
df_dokter_filtered.groupby('NO_REG')['NM_UNIT'].nunique().value_counts()

NM_UNIT
1    4281
Name: count, dtype: int64

Hapus yang tidak ada diagnosa penyakit

In [21]:
df_dokter_filtered = df_dokter_filtered[df_dokter_filtered['NM_PENYAKIT'].notna()]

In [22]:
df_dokter_filtered.info()

<class 'pandas.core.frame.DataFrame'>
Index: 4257 entries, 3 to 22639
Data columns (total 13 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   NO_REG         4257 non-null   int64
 1   TGL_LAHIR_F    4257 non-null   object
 2   JENIS_KELAMIN  4257 non-null   object
 3   UMUR_TAHUN     4257 non-null   float64
 4   UMUR_BULAN     4257 non-null   float64
 5   UMUR_HARI      4257 non-null   float64
 6   NM_UNIT        4257 non-null   object
 7   ASESMEN        4248 non-null   object
 8   SUBYEKTIF      4257 non-null   object
 9   OBYEKTIF       4237 non-null   object
 10  KD_PENYAKIT    4257 non-null   object
 11  NM_PENYAKIT    4257 non-null   object
 12  bulan          4257 non-null   object
dtypes: float64(3), int64(1), object(9)
memory usage: 465.6+ KB

In [23]:
df_dokter_filtered.to_csv('dokter_filtered.csv', index=False)