# Import LIibrary & Data

In [ ]:
import pandas as pd
from sklearn.preprocessing import LabelEncoder
import statsmodels.api as sm

In [ ]:
df_lab = pd.read_csv('df_lab_selected.csv')

In [ ]:
df_lab.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2467 entries, 0 to 2466
Columns: 112 entries, NO_REG to wbc
dtypes: float64(109), int64(1), object(2)
memory usage: 2.1+ MB

In [ ]:
df_lab

,NO_REG,TGL_INPUT,NM_PERIKSA,aa do2,albumin,amilum,amoeba,amphetamine,anti hcv,asam urat,...,thc,trigliserida,troponin i high sensitive,tsh,tubex tf,ureum,urine protein,urobilinogen,warna,wbc
0,10579978,2026-02-05 09:14:00,urin lengkap,NaN,NaN,NaN,NaN,NaN,NaN,9.32,...,NaN,207.0,NaN,NaN,NaN,24.0,NaN,0.2,NaN,NaN
1,10580957,2026-02-06 09:06:00,lemak,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,205.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,10581496,2026-02-06 19:25:00,ureum,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,67.0,NaN,NaN,NaN,NaN
3,10582858,2026-02-03 11:56:00,lemak,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,206.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,10583233,2026-02-11 18:19:00,ureum,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,75.0,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2462,10622311,2026-04-29 09:39:00,hematologi rutin,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,9.0
2463,10622354,2026-04-29 11:09:00,ureum,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,44.0,NaN,NaN,NaN,8.4
2464,10622360,2026-04-29 11:33:00,ureum,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,32.0,NaN,NaN,NaN,6.9
2465,10622389,2026-04-29 12:42:00,urin lengkap,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.2,NaN,9.6
2466,10622394,2026-04-29 13:22:00,ureum,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,51.0,NaN,NaN,NaN,8.8

In [ ]:
df_dokter = pd.read_csv('dokter_filtered.csv')

In [ ]:
df_dokter.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4257 entries, 0 to 4256
Data columns (total 12 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   NO_REG         4257 non-null   int64
 1   TGL_LAHIR_F    4257 non-null   object
 2   JENIS_KELAMIN  4257 non-null   object
 3   UMUR_TAHUN     4257 non-null   float64
 4   UMUR_BULAN     4257 non-null   float64
 5   UMUR_HARI      4257 non-null   float64
 6   NM_UNIT        4257 non-null   object
 7   ASESMEN        4248 non-null   object
 8   SUBYEKTIF      4257 non-null   object
 9   OBYEKTIF       4237 non-null   object
 10  KD_PENYAKIT    4257 non-null   object
 11  NM_PENYAKIT    4257 non-null   object
dtypes: float64(3), int64(1), object(8)
memory usage: 399.2+ KB

# Merge Data

In [ ]:
df_lab['NO_REG'] = df_lab['NO_REG'].astype(int)
df_dokter['NO_REG'] = df_dokter['NO_REG'].astype(int)

In [ ]:
df_lab['HAS_LAB'] = 1
df_dokter['HAS_DOCTOR'] = 1

In [ ]:
df_merge = pd.merge(
    df_dokter,
    df_lab,
    on='NO_REG',
    how='outer'
)

In [ ]:
df_merge['HAS_LAB'] = df_merge['HAS_LAB'].fillna(0)
df_merge['HAS_DOCTOR'] = df_merge['HAS_DOCTOR'].fillna(0)

In [ ]:
df_merge.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6430 entries, 0 to 6429
Columns: 125 entries, NO_REG to HAS_LAB
dtypes: float64(114), int64(1), object(10)
memory usage: 6.1+ MB

In [ ]:
#df_final.to_csv('df_merge_dokter_filter.csv', index=False)

In [ ]:
df_merge[['HAS_LAB', 'HAS_DOCTOR']].value_counts()

HAS_LAB  HAS_DOCTOR
0.0      1.0           3963
1.0      0.0           2173
         1.0            294
Name: count, dtype: int64

# Feature Selection

In [ ]:
selected_features = [
    'NO_REG',
    'JENIS_KELAMIN',
    'UMUR_TAHUN',
    'cholesterol total',
    'creatinin',
    'glukosa darah puasa',
    'glukosa darah sewaktu',
    'hgb',
    'lymfosit%',
    'mch',
    'mchc',
    'mcv',
    'ureum',
    'wbc',
    'NM_UNIT'
]

In [ ]:
df_clean = df_merge[selected_features].copy()

In [ ]:
df_clean = df_clean.rename(columns={
    'glukosa darah puasa': 'fbs',
    'glukosa darah sewaktu': 'rbs'
})

In [ ]:
df_clean.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6430 entries, 0 to 6429
Data columns (total 15 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   NO_REG             6430 non-null   int64
 1   JENIS_KELAMIN      4257 non-null   object
 2   UMUR_TAHUN         4257 non-null   float64
 3   cholesterol total  141 non-null    float64
 4   creatinin          895 non-null    float64
 5   fbs                68 non-null     float64
 6   rbs                847 non-null    float64
 7   hgb                2164 non-null   float64
 8   lymfosit%          1831 non-null   float64
 9   mch                1836 non-null   float64
 10  mchc               1836 non-null   float64
 11  mcv                1836 non-null   float64
 12  ureum              796 non-null    float64
 13  wbc                1837 non-null   float64
 14  NM_UNIT            4257 non-null   object
dtypes: float64(12), int64(1), object(2)
memory usage: 753.6+ KB

# Data Transformation

In [ ]:
# Encode gender
gender_encoder = LabelEncoder()
df_clean['JENIS_KELAMIN'] = gender_encoder.fit_transform(df_clean['JENIS_KELAMIN'])

In [ ]:
# Mapping target
mapping_nm_unit = {
    'JANTUNG DAN PEMBULUH DARAH': 1,
    'SPES. PENYAKIT DALAM': 2,
    'SPES. PARU PARU': 3
}

df_clean['NM_UNIT'] = df_clean['NM_UNIT'].map(mapping_nm_unit)

# Isi NaN target menjadi 0
df_clean['NM_UNIT'] = df_clean['NM_UNIT'].fillna(0)

In [ ]:
# Drop kolom yang tidak dipakai
df_clean = df_clean.drop(columns=['NO_REG'])

In [ ]:
df_clean.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6430 entries, 0 to 6429
Data columns (total 14 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   JENIS_KELAMIN      6430 non-null   int64
 1   UMUR_TAHUN         4257 non-null   float64
 2   cholesterol total  141 non-null    float64
 3   creatinin          895 non-null    float64
 4   fbs                68 non-null     float64
 5   rbs                847 non-null    float64
 6   hgb                2164 non-null   float64
 7   lymfosit%          1831 non-null   float64
 8   mch                1836 non-null   float64
 9   mchc               1836 non-null   float64
 10  mcv                1836 non-null   float64
 11  ureum              796 non-null    float64
 12  wbc                1837 non-null   float64
 13  NM_UNIT            6430 non-null   float64
dtypes: float64(13), int64(1)
memory usage: 703.4 KB

In [ ]:
# Simpan dataset bersih
df_clean.to_csv('merge_DocLab_Clean.csv', index=False)